# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            lcapkovic.xyz
tagline:          'A site'
description:      'Test description'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Lukas Capkovic'
  url:            http://github.com/lcapkovic

paginate:         5

# Custom vars
version:          0.5

github:
  repo:           https://github.com/poole/hyde
